[2025-03-11T18:30:04.706+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-11T18:30:04.730+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.ingest_data.ingest_crm_data scheduled__2025-03-11T18:15:00+00:00 [queued]>
[2025-03-11T18:30:04.739+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.ingest_data.ingest_crm_data scheduled__2025-03-11T18:15:00+00:00 [queued]>
[2025-03-11T18:30:04.739+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-11T18:30:04.757+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ingest_data.ingest_crm_data> on 2025-03-11 18:15:00+00:00
[2025-03-11T18:30:04.766+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=460) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T18:30:04.768+0000] {standard_task_runner.py:63} INFO - Started process 463 to run task
[2025-03-11T18:30:04.768+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'ingest_data.ingest_crm_data', 'scheduled__2025-03-11T18:15:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpfrt9lknk']
[2025-03-11T18:30:04.771+0000] {standard_task_runner.py:91} INFO - Job 144: Subtask ingest_data.ingest_crm_data
[2025-03-11T18:30:04.813+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.ingest_data.ingest_crm_data scheduled__2025-03-11T18:15:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-11T18:30:04.931+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='ingest_data.ingest_crm_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T18:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T18:15:00+00:00'
[2025-03-11T18:30:04.932+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-11T18:30:05.027+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
  warn_incompatible_dep(

[2025-03-11T18:30:05.137+0000] {connection.py:423} INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.12.2, Platform: Linux-6.11.0-19-generic-x86_64-with-glibc2.36
[2025-03-11T18:30:05.138+0000] {connection.py:1226} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-11T18:30:05.139+0000] {connection.py:1315} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-11T18:30:05.930+0000] {snowflake_utilz.py:13} INFO - Connected to snowflake successfully
[2025-03-11T18:30:05.936+0000] {snowflake_utilz.py:26} INFO - Connected to PostgreSQL database successfully
[2025-03-11T18:30:05.937+0000] {pipeline.py:77} INFO - ðŸ“¥ Ingesting CRM data...
[2025-03-11T18:30:05.938+0000] {ingest_data.py:12} INFO - File cust_info.csv has already been processed. Skipping ingestion.
[2025-03-11T18:30:05.939+0000] {ingest_data.py:12} INFO - File prd_info.csv has already been processed. Skipping ingestion.
[2025-03-11T18:30:05.939+0000] {ingest_data.py:12} INFO - File sales_details.csv has already been processed. Skipping ingestion.
[2025-03-11T18:30:06.035+0000] {snowflake_utilz.py:35} INFO - connection is closed
[2025-03-11T18:30:06.035+0000] {connection.py:810} INFO - closed
[2025-03-11T18:30:06.107+0000] {connection.py:816} INFO - No async queries seem to be running, deleting session
[2025-03-11T18:30:06.203+0000] {snowflake_utilz.py:38} INFO - SQLAlchemy engine disposed
[2025-03-11T18:30:06.204+0000] {snowflake_utilz.py:35} INFO - connection is closed
[2025-03-11T18:30:06.204+0000] {snowflake_utilz.py:38} INFO - SQLAlchemy engine disposed
[2025-03-11T18:30:06.204+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-03-11T18:30:06.205+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-11T18:30:06.214+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=ingest_data.ingest_crm_data, execution_date=20250311T181500, start_date=20250311T183004, end_date=20250311T183006
[2025-03-11T18:30:06.265+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-11T18:30:06.288+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-11T18:30:06.290+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
