[2025-03-13T20:30:17.462+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-13T20:30:17.504+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.silver_layer.erp_customer_loc scheduled__2025-03-13T20:15:00+00:00 [queued]>
[2025-03-13T20:30:17.518+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.silver_layer.erp_customer_loc scheduled__2025-03-13T20:15:00+00:00 [queued]>
[2025-03-13T20:30:17.518+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-13T20:30:17.540+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): silver_layer.erp_customer_loc> on 2025-03-13 20:15:00+00:00
[2025-03-13T20:30:17.550+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=995) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T20:30:17.552+0000] {standard_task_runner.py:63} INFO - Started process 1011 to run task
[2025-03-13T20:30:17.553+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'silver_layer.erp_customer_loc', 'scheduled__2025-03-13T20:15:00+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpj9yjq3en']
[2025-03-13T20:30:17.556+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask silver_layer.erp_customer_loc
[2025-03-13T20:30:17.625+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.silver_layer.erp_customer_loc scheduled__2025-03-13T20:15:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-13T20:30:17.796+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='silver_layer.erp_customer_loc' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T20:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T20:15:00+00:00'
[2025-03-13T20:30:17.798+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-13T20:30:17.826+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-13T20:30:17.827+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --full-refresh --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/sales --models erp_customer_loc']
[2025-03-13T20:30:17.853+0000] {subprocess.py:86} INFO - Output:
[2025-03-13T20:30:22.105+0000] {subprocess.py:93} INFO - [0m20:30:22  Running with dbt=1.9.3
[2025-03-13T20:30:23.234+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-03-13T20:30:23.235+0000] {subprocess.py:93} INFO -   warn_incompatible_dep(
[2025-03-13T20:30:24.579+0000] {subprocess.py:93} INFO - [0m20:30:24  Registered adapter: snowflake=1.9.2
[2025-03-13T20:30:25.901+0000] {subprocess.py:93} INFO - [0m20:30:25  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-13T20:30:25.902+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-13T20:30:25.902+0000] {subprocess.py:93} INFO - - models.sales.Gold_layer
[2025-03-13T20:30:26.521+0000] {subprocess.py:93} INFO - [0m20:30:26  Found 6 models, 35 data tests, 6 sources, 855 macros
[2025-03-13T20:30:26.527+0000] {subprocess.py:93} INFO - [0m20:30:26
[2025-03-13T20:30:26.528+0000] {subprocess.py:93} INFO - [0m20:30:26  Concurrency: 2 threads (target='dev')
[2025-03-13T20:30:26.529+0000] {subprocess.py:93} INFO - [0m20:30:26
[2025-03-13T20:30:27.631+0000] {subprocess.py:93} INFO - [0m20:30:27  1 of 1 START sql incremental model layer_silver.erp_customer_loc ............... [RUN]
[2025-03-13T20:31:31.439+0000] {subprocess.py:93} INFO - [0m20:31:31  1 of 1 OK created sql incremental model layer_silver.erp_customer_loc .......... [[32mSUCCESS 1[0m in 63.81s]
[2025-03-13T20:31:31.596+0000] {subprocess.py:93} INFO - [0m20:31:31
[2025-03-13T20:31:31.596+0000] {subprocess.py:93} INFO - [0m20:31:31  Finished running 1 incremental model in 0 hours 1 minutes and 5.07 seconds (65.07s).
[2025-03-13T20:31:31.693+0000] {subprocess.py:93} INFO - [0m20:31:31
[2025-03-13T20:31:31.693+0000] {subprocess.py:93} INFO - [0m20:31:31  [32mCompleted successfully[0m
[2025-03-13T20:31:31.694+0000] {subprocess.py:93} INFO - [0m20:31:31
[2025-03-13T20:31:31.694+0000] {subprocess.py:93} INFO - [0m20:31:31  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-03-13T20:31:33.167+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-13T20:31:33.168+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-13T20:31:33.206+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=silver_layer.erp_customer_loc, execution_date=20250313T201500, start_date=20250313T203017, end_date=20250313T203133
[2025-03-13T20:31:33.249+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-13T20:31:33.319+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T20:31:33.320+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
