[2025-03-11T12:15:08.157+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-11T12:15:08.186+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.dbt_test_connection scheduled__2025-03-11T12:00:00+00:00 [queued]>
[2025-03-11T12:15:08.194+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.dbt_test_connection scheduled__2025-03-11T12:00:00+00:00 [queued]>
[2025-03-11T12:15:08.195+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-11T12:15:08.209+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_test_connection> on 2025-03-11 12:00:00+00:00
[2025-03-11T12:15:08.221+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=263) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T12:15:08.222+0000] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2025-03-11T12:15:08.223+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'dbt_test_connection', 'scheduled__2025-03-11T12:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp4i7zqhep']
[2025-03-11T12:15:08.225+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask dbt_test_connection
[2025-03-11T12:15:08.274+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.dbt_test_connection scheduled__2025-03-11T12:00:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-11T12:15:08.376+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T12:00:00+00:00'
[2025-03-11T12:15:08.378+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-11T12:15:08.396+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-11T12:15:08.397+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/sales']
[2025-03-11T12:15:08.419+0000] {subprocess.py:86} INFO - Output:
[2025-03-11T12:15:10.867+0000] {subprocess.py:93} INFO - [0m12:15:10  Encountered an error:
[2025-03-11T12:15:10.867+0000] {subprocess.py:93} INFO - [Errno 13] Permission denied: '/opt/***/dbt/sales/logs/dbt.log'
[2025-03-11T12:15:10.870+0000] {subprocess.py:93} INFO - [0m12:15:10  Traceback (most recent call last):
[2025-03-11T12:15:10.870+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 153, in wrapper
[2025-03-11T12:15:10.871+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2025-03-11T12:15:10.871+0000] {subprocess.py:93} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2025-03-11T12:15:10.871+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 79, in wrapper
[2025-03-11T12:15:10.871+0000] {subprocess.py:93} INFO -     setup_event_logger(flags=flags, callbacks=callbacks)
[2025-03-11T12:15:10.872+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/events/logging.py", line 100, in setup_event_logger
[2025-03-11T12:15:10.872+0000] {subprocess.py:93} INFO -     add_logger_to_manager(
[2025-03-11T12:15:10.872+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/events/event_manager_client.py", line 17, in add_logger_to_manager
[2025-03-11T12:15:10.872+0000] {subprocess.py:93} INFO -     _EVENT_MANAGER.add_logger(logger)
[2025-03-11T12:15:10.873+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/events/event_manager.py", line 36, in add_logger
[2025-03-11T12:15:10.873+0000] {subprocess.py:93} INFO -     _JsonLogger(config) if config.line_format == LineFormat.Json else _TextLogger(config)
[2025-03-11T12:15:10.873+0000] {subprocess.py:93} INFO -                                                                       ^^^^^^^^^^^^^^^^^^^
[2025-03-11T12:15:10.873+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/events/logger.py", line 147, in __init__
[2025-03-11T12:15:10.873+0000] {subprocess.py:93} INFO -     super().__init__(config)
[2025-03-11T12:15:10.873+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/events/logger.py", line 107, in __init__
[2025-03-11T12:15:10.874+0000] {subprocess.py:93} INFO -     file_handler = RotatingFileHandler(
[2025-03-11T12:15:10.874+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^
[2025-03-11T12:15:10.874+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/logging/handlers.py", line 155, in __init__
[2025-03-11T12:15:10.874+0000] {subprocess.py:93} INFO -     BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
[2025-03-11T12:15:10.874+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/logging/handlers.py", line 58, in __init__
[2025-03-11T12:15:10.874+0000] {subprocess.py:93} INFO -     logging.FileHandler.__init__(self, filename, mode=mode,
[2025-03-11T12:15:10.875+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1231, in __init__
[2025-03-11T12:15:10.875+0000] {subprocess.py:93} INFO -     StreamHandler.__init__(self, self._open())
[2025-03-11T12:15:10.875+0000] {subprocess.py:93} INFO -                                  ^^^^^^^^^^^^
[2025-03-11T12:15:10.875+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1263, in _open
[2025-03-11T12:15:10.875+0000] {subprocess.py:93} INFO -     return open_func(self.baseFilename, self.mode,
[2025-03-11T12:15:10.875+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-11T12:15:10.876+0000] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: '/opt/***/dbt/sales/logs/dbt.log'
[2025-03-11T12:15:10.876+0000] {subprocess.py:93} INFO - 
[2025-03-11T12:15:11.191+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-03-11T12:15:11.192+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-11T12:15:11.202+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-03-11T12:15:11.205+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sales_pipeline, task_id=dbt_test_connection, execution_date=20250311T120000, start_date=20250311T121508, end_date=20250311T121511
[2025-03-11T12:15:11.220+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 113 for task dbt_test_connection (Bash command failed. The command returned a non-zero exit code 2.; 265)
[2025-03-11T12:15:11.243+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-11T12:15:11.258+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T12:15:11.259+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
