[2025-03-14T01:04:55.785+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-14T01:04:55.813+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.test_quality.Fact_sales scheduled__2025-03-14T00:45:00+00:00 [queued]>
[2025-03-14T01:04:55.824+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.test_quality.Fact_sales scheduled__2025-03-14T00:45:00+00:00 [queued]>
[2025-03-14T01:04:55.824+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-14T01:04:55.897+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): test_quality.Fact_sales> on 2025-03-14 00:45:00+00:00
[2025-03-14T01:04:55.908+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2335) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T01:04:55.909+0000] {standard_task_runner.py:63} INFO - Started process 2343 to run task
[2025-03-14T01:04:55.909+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'test_quality.Fact_sales', 'scheduled__2025-03-14T00:45:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp_6jwu0zm']
[2025-03-14T01:04:55.912+0000] {standard_task_runner.py:91} INFO - Job 236: Subtask test_quality.Fact_sales
[2025-03-14T01:04:56.004+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.test_quality.Fact_sales scheduled__2025-03-14T00:45:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-14T01:04:56.214+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='test_quality.Fact_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T00:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-14T00:45:00+00:00'
[2025-03-14T01:04:56.215+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-14T01:04:56.228+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-14T01:04:56.229+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt test  --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/sales --models Fact_sales']
[2025-03-14T01:04:56.249+0000] {subprocess.py:86} INFO - Output:
[2025-03-14T01:04:59.552+0000] {subprocess.py:93} INFO - [0m01:04:59  Running with dbt=1.9.3
[2025-03-14T01:05:00.397+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-03-14T01:05:00.398+0000] {subprocess.py:93} INFO -   warn_incompatible_dep(
[2025-03-14T01:05:01.228+0000] {subprocess.py:93} INFO - [0m01:05:01  Registered adapter: snowflake=1.9.2
[2025-03-14T01:05:02.472+0000] {subprocess.py:93} INFO - [0m01:05:02  Found 10 models, 41 data tests, 6 sources, 855 macros
[2025-03-14T01:05:02.474+0000] {subprocess.py:93} INFO - [0m01:05:02  Nothing to do. Try checking your model configs and model specification args
[2025-03-14T01:05:03.828+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-14T01:05:03.828+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-14T01:05:03.885+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=test_quality.Fact_sales, execution_date=20250314T004500, start_date=20250314T010455, end_date=20250314T010503
[2025-03-14T01:05:03.959+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-14T01:05:04.024+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T01:05:04.098+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
