[2025-03-10T19:30:04.699+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-10T19:30:04.720+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.ingest_crm_data scheduled__2025-03-10T19:15:00+00:00 [queued]>
[2025-03-10T19:30:04.728+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.ingest_crm_data scheduled__2025-03-10T19:15:00+00:00 [queued]>
[2025-03-10T19:30:04.728+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-10T19:30:04.739+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): ingest_crm_data> on 2025-03-10 19:15:00+00:00
[2025-03-10T19:30:04.748+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T19:30:04.749+0000] {standard_task_runner.py:63} INFO - Started process 73 to run task
[2025-03-10T19:30:04.749+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'ingest_crm_data', 'scheduled__2025-03-10T19:15:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp7m1a3zg8']
[2025-03-10T19:30:04.751+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask ingest_crm_data
[2025-03-10T19:30:04.791+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.ingest_crm_data scheduled__2025-03-10T19:15:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-10T19:30:04.878+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='ingest_crm_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T19:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-10T19:15:00+00:00'
[2025-03-10T19:30:04.879+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-10T19:30:04.970+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
  warn_incompatible_dep(

[2025-03-10T19:30:05.060+0000] {connection.py:423} INFO - Snowflake Connector for Python Version: 3.14.0, Python Version: 3.12.2, Platform: Linux-6.11.0-19-generic-x86_64-with-glibc2.36
[2025-03-10T19:30:05.061+0000] {connection.py:1226} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-10T19:30:05.061+0000] {connection.py:1315} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-10T19:30:05.758+0000] {snowflake_utilz.py:13} INFO - Connected to snowflake successfully
[2025-03-10T19:30:05.764+0000] {snowflake_utilz.py:26} INFO - Connected to PostgreSQL database successfully
[2025-03-10T19:30:05.764+0000] {pipeline.py:76} INFO - ðŸ“¥ Ingesting CRM data...
[2025-03-10T19:30:05.764+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-10T19:30:05.764+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline.py", line 79, in ingest_crm_data
    crm_cus = os.path.join(crm_path, "cust_info.csv")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-03-10T19:30:05.772+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=sales_pipeline, task_id=ingest_crm_data, execution_date=20250310T191500, start_date=20250310T193004, end_date=20250310T193005
[2025-03-10T19:30:05.783+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task ingest_crm_data (expected str, bytes or os.PathLike object, not NoneType; 73)
[2025-03-10T19:30:05.805+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-10T19:30:05.818+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T19:30:05.820+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
