[2025-03-13T20:15:35.368+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-13T20:15:35.415+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_pipeline.test_validating_data_silver_layer.erp_customer_loc scheduled__2025-03-13T20:00:00+00:00 [queued]>
[2025-03-13T20:15:35.429+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_pipeline.test_validating_data_silver_layer.erp_customer_loc scheduled__2025-03-13T20:00:00+00:00 [queued]>
[2025-03-13T20:15:35.430+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-03-13T20:15:35.460+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): test_validating_data_silver_layer.erp_customer_loc> on 2025-03-13 20:00:00+00:00
[2025-03-13T20:15:35.473+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=848) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T20:15:35.476+0000] {standard_task_runner.py:63} INFO - Started process 857 to run task
[2025-03-13T20:15:35.476+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sales_pipeline', 'test_validating_data_silver_layer.erp_customer_loc', 'scheduled__2025-03-13T20:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp8twd4tvu']
[2025-03-13T20:15:35.480+0000] {standard_task_runner.py:91} INFO - Job 193: Subtask test_validating_data_silver_layer.erp_customer_loc
[2025-03-13T20:15:35.566+0000] {task_command.py:426} INFO - Running <TaskInstance: sales_pipeline.test_validating_data_silver_layer.erp_customer_loc scheduled__2025-03-13T20:00:00+00:00 [running]> on host 2b35ac7f54da
[2025-03-13T20:15:35.769+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='sales_pipeline' AIRFLOW_CTX_TASK_ID='test_validating_data_silver_layer.erp_customer_loc' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T20:00:00+00:00'
[2025-03-13T20:15:35.771+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-13T20:15:35.808+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-13T20:15:35.809+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --full-refresh --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/sales --models erp_customer_loc']
[2025-03-13T20:15:35.846+0000] {subprocess.py:86} INFO - Output:
[2025-03-13T20:15:40.625+0000] {subprocess.py:93} INFO - [0m20:15:40  Running with dbt=1.9.3
[2025-03-13T20:15:41.780+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/snowflake/connector/options.py:108: UserWarning: You have an incompatible version of 'pyarrow' installed (19.0.1), please install a version that adheres to: 'pyarrow<19.0.0; extra == "pandas"'
[2025-03-13T20:15:41.781+0000] {subprocess.py:93} INFO -   warn_incompatible_dep(
[2025-03-13T20:15:42.834+0000] {subprocess.py:93} INFO - [0m20:15:42  Registered adapter: snowflake=1.9.2
[2025-03-13T20:15:43.738+0000] {subprocess.py:93} INFO - [0m20:15:43  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-13T20:15:43.740+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-13T20:15:43.740+0000] {subprocess.py:93} INFO - - models.sales.Gold_layer
[2025-03-13T20:15:44.306+0000] {subprocess.py:93} INFO - [0m20:15:44  Found 6 models, 35 data tests, 6 sources, 855 macros
[2025-03-13T20:15:44.311+0000] {subprocess.py:93} INFO - [0m20:15:44
[2025-03-13T20:15:44.313+0000] {subprocess.py:93} INFO - [0m20:15:44  Concurrency: 2 threads (target='dev')
[2025-03-13T20:15:44.315+0000] {subprocess.py:93} INFO - [0m20:15:44
[2025-03-13T20:15:45.483+0000] {subprocess.py:93} INFO - [0m20:15:45  1 of 1 START sql incremental model layer_silver.erp_customer_loc ............... [RUN]
[2025-03-13T20:15:46.439+0000] {subprocess.py:93} INFO - [0m20:15:46  1 of 1 OK created sql incremental model layer_silver.erp_customer_loc .......... [[32mSUCCESS 1[0m in 0.95s]
[2025-03-13T20:15:46.593+0000] {subprocess.py:93} INFO - [0m20:15:46
[2025-03-13T20:15:46.594+0000] {subprocess.py:93} INFO - [0m20:15:46  Finished running 1 incremental model in 0 hours 0 minutes and 2.28 seconds (2.28s).
[2025-03-13T20:15:46.668+0000] {subprocess.py:93} INFO - [0m20:15:46
[2025-03-13T20:15:46.669+0000] {subprocess.py:93} INFO - [0m20:15:46  [32mCompleted successfully[0m
[2025-03-13T20:15:46.669+0000] {subprocess.py:93} INFO - [0m20:15:46
[2025-03-13T20:15:46.670+0000] {subprocess.py:93} INFO - [0m20:15:46  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-03-13T20:15:47.947+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-13T20:15:47.949+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-13T20:15:47.994+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=sales_pipeline, task_id=test_validating_data_silver_layer.erp_customer_loc, execution_date=20250313T200000, start_date=20250313T201535, end_date=20250313T201547
[2025-03-13T20:15:48.039+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-13T20:15:48.058+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T20:15:48.059+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
